services:
  - type: web
    name: grace-portfolio
    env: php
    region: frankfurt
    plan: free
    buildCommand: echo "Préparation du déploiement"
    startCommand: php -S 0.0.0.0:$PORT
    staticPublicPath: /
    envVars:
      - key: PHP_VERSION
        value: 8.2
